import enum

class ProcessingType(enum.Enum):
    CHECK_PARSABILITY="CHECK_PARSABILITY"
    COMPUTE_SOLUTION_NORM_BOUND="COMPUTE_SOLUTION_NORM_BOUND"
    COMPUTE_GRADIENT_NORM_BOUND="COMPUTE_GRADIENT_NORM_BOUND"
    COMPUTE_LOSS="COMPUTE_LOSS"
    COMPUTE_FUNCTION="COMPUTE_FUNCTION"
    COMPUTE_GRADIENT="COMPUTE_GRADIENT"
    COMPUTE_MSTEP_FUNCTION="COMPUTE_MSTEP_FUNCTION"
    COMPUTE_MSTEP_GRADIENT="COMPUTE_MSTEP_GRADIENT"
    COMPUTE_GAMMAMLE_FUNCTION="COMPUTE_GAMMAMLE_FUNCTION"
    COMPUTE_GAMMAMLE_GRADIENT="COMPUTE_GAMMAMLE_GRADIENT"
    COMPUTE_GAMMAMLE_SCALING_FACTOR="COMPUTE_GAMMAMLE_SCALING_FACTOR"
    COMPUTE_FUNCTION_SE="COMPUTE_FUNCTION_SE"
    COMPUTE_GRADIENT_SE="COMPUTE_GRADIENT_SE"
    CHECK_ZEROS_IN_DATA="CHECK_ZEROS_IN_DATA"
    COMPUTE_HV="COMPUTE_HV"
    PREDICT="PREDICT"
    